# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mydesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GEO_OTVAL(object):
    def setupUi(self, GEO_OTVAL):
        GEO_OTVAL.setObjectName("GEO_OTVAL")
        GEO_OTVAL.resize(598, 258)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        GEO_OTVAL.setFont(font)
        GEO_OTVAL.setAutoFillBackground(False)
        GEO_OTVAL.setStyleSheet("background-color: rgb(35, 36, 41);")
        GEO_OTVAL.setAnimated(True)
        GEO_OTVAL.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(GEO_OTVAL)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 10, 511, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(49, 52, 58);\n"
"border-radius: 10%;\n"
"color: rgb(255, 255, 255)")
        self.pushButton.setObjectName("pushButton")
        self.edit_x = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_x.setGeometry(QtCore.QRect(380, 110, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.edit_x.setFont(font)
        self.edit_x.setStyleSheet("background-color: rgb(49, 52, 58);\n"
"border-radius: 10%;\n"
"color: rgb(255, 255, 255)")
        self.edit_x.setPlaceholderText("")
        self.edit_x.setObjectName("edit_x")
        self.makeMap = QtWidgets.QPushButton(self.centralwidget)
        self.makeMap.setGeometry(QtCore.QRect(20, 70, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.makeMap.setFont(font)
        self.makeMap.setStyleSheet("background-color: rgb(49, 52, 58);\n"
"border-radius: 10%;\n"
"color: rgb(255, 255, 255)")
        self.makeMap.setObjectName("makeMap")
        self.makeClear = QtWidgets.QPushButton(self.centralwidget)
        self.makeClear.setGeometry(QtCore.QRect(480, 110, 111, 81))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.makeClear.setFont(font)
        self.makeClear.setStyleSheet("background-color: rgb(49, 52, 58);\n"
"border-radius: 10%;\n"
"color: rgb(255, 255, 255)")
        self.makeClear.setObjectName("makeClear")
        self.x = QtWidgets.QLabel(self.centralwidget)
        self.x.setGeometry(QtCore.QRect(340, 110, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.x.setFont(font)
        self.x.setStyleSheet("background-color: rgb(49, 52, 58);\n"
"border-radius: 10%;\n"
"color: rgb(255, 255, 255)")
        self.x.setObjectName("x")
        self.y = QtWidgets.QLabel(self.centralwidget)
        self.y.setGeometry(QtCore.QRect(340, 160, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.y.setFont(font)
        self.y.setStyleSheet("background-color: rgb(49, 52, 58);\n"
"border-radius: 10%;\n"
"color: rgb(255, 255, 255)")
        self.y.setObjectName("y")
        self.edit_y = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_y.setGeometry(QtCore.QRect(380, 160, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.edit_y.setFont(font)
        self.edit_y.setStyleSheet("background-color: rgb(49, 52, 58);\n"
"border-radius: 10%;\n"
"color: rgb(255, 255, 255)")
        self.edit_y.setPlaceholderText("")
        self.edit_y.setObjectName("edit_y")
        self.start = QtWidgets.QLabel(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(380, 70, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.start.setFont(font)
        self.start.setStyleSheet("background-color: rgb(49, 52, 58);\n"
"border-radius: 10%;\n"
"color: rgb(255, 255, 255)")
        self.start.setObjectName("start")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(550, 10, 41, 41))
        self.exit.setStyleSheet("border-radius: 10%;\n"
"background-color: red;")
        self.exit.setObjectName("exit")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 180, 121, 31))
        self.lineEdit.setStyleSheet("background-color: rgb(49, 52, 58);\n"
"border-radius: 10%;\n"
"color: rgb(255, 255, 255)")
        self.lineEdit.setObjectName("lineEdit")
        self.otr = QtWidgets.QComboBox(self.centralwidget)
        self.otr.setGeometry(QtCore.QRect(150, 180, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        self.otr.setFont(font)
        self.otr.setStyleSheet("background-color: rgb(49, 52, 58);\n"
"color: rgb(255, 255, 255);")
        self.otr.setObjectName("otr")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 120, 151, 21))
        self.lineEdit_2.setStyleSheet("background-color: rgb(49, 52, 58);\n"
"border-radius: 10%;\n"
"color: rgb(255, 255, 255)")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(190, 120, 141, 20))
        self.lineEdit_4.setStyleSheet("background-color: rgb(49, 52, 58);\n"
"border-radius: 10%;\n"
"color: rgb(255, 255, 255)")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(190, 150, 141, 20))
        self.lineEdit_5.setStyleSheet("background-color: rgb(49, 52, 58);\n"
"border-radius: 10%;\n"
"color: rgb(255, 255, 255)")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(20, 150, 151, 21))
        self.lineEdit_3.setStyleSheet("background-color: rgb(49, 52, 58);\n"
"border-radius: 10%;\n"
"color: rgb(255, 255, 255)")
        self.lineEdit_3.setObjectName("lineEdit_3")
        GEO_OTVAL.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(GEO_OTVAL)
        self.statusbar.setObjectName("statusbar")
        GEO_OTVAL.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(GEO_OTVAL)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 598, 21))
        self.menubar.setObjectName("menubar")
        GEO_OTVAL.setMenuBar(self.menubar)

        self.retranslateUi(GEO_OTVAL)
        self.makeClear.clicked.connect(self.edit_x.clear)
        self.makeClear.clicked.connect(self.edit_y.clear)
        QtCore.QMetaObject.connectSlotsByName(GEO_OTVAL)

    def retranslateUi(self, GEO_OTVAL):
        _translate = QtCore.QCoreApplication.translate
        GEO_OTVAL.setWindowTitle(_translate("GEO_OTVAL", "MainWindow"))
        self.pushButton.setText(_translate("GEO_OTVAL", "Загрузить изображение"))
        self.edit_x.setText(_translate("GEO_OTVAL", "4183642"))
        self.makeMap.setText(_translate("GEO_OTVAL", "Создать карту с заданными параметрами"))
        self.makeClear.setText(_translate("GEO_OTVAL", "Очистить"))
        self.x.setText(_translate("GEO_OTVAL", "  x = "))
        self.y.setText(_translate("GEO_OTVAL", "  y = "))
        self.edit_y.setText(_translate("GEO_OTVAL", "7529089"))
        self.start.setText(_translate("GEO_OTVAL", "  Координаты в кодировке EPSG:3857"))
        self.exit.setText(_translate("GEO_OTVAL", "x"))
        self.lineEdit.setPlaceholderText(_translate("GEO_OTVAL", " Введите расстояние"))
        self.lineEdit_2.setPlaceholderText(_translate("GEO_OTVAL", "Доп. точка 1-X"))
        self.lineEdit_4.setPlaceholderText(_translate("GEO_OTVAL", "Доп. точка 2-X"))
        self.lineEdit_5.setPlaceholderText(_translate("GEO_OTVAL", "Доп. точка 2-Y"))
        self.lineEdit_3.setPlaceholderText(_translate("GEO_OTVAL", "Доп. точка 1-Y"))
